ALTER TABLE [dbo].[ENTRADAS_IMPORTACION] ALTER COLUMN [CERTIFICADO_ZOOSANITARIO] VARCHAR (50) NULL;
ALTER TABLE [dbo].[ENTRADAS] ADD [ESTATUS_FACTURA_IMPORTACION] INT NULL;
ALTER TABLE [dbo].[ENTRADAS_IMPORTACION] DROP CONSTRAINT [FK_ENTRADAS_IMPORTACION_PROVEEDORES_IMPORTACION];
ALTER TABLE [dbo].[ENTRADAS_IMPORTACION] ADD [FOLIO_IMPORTACION] BIGINT NULL;
