CREATE TABLE [dbo].[BITACORA_PRECIOS] (
    [ID_PRECIO_BITACORA]  INT             IDENTITY (1, 1) NOT NULL,
    [ID_MATERIA]          INT             NULL,
    [ID_PROVEEDOR]        INT             NULL,
    [PRECIO_ACTUAL]       DECIMAL (10, 4) NULL,
    [FECHA_ACTUALIZACION] DATETIME        NULL,
    [ACTUALIZADO_POR]     INT             NULL,
    CONSTRAINT [PK_BITACORA_PRECIOS] PRIMARY KEY CLUSTERED ([ID_PRECIO_BITACORA] ASC)
);
