CREATE TABLE [dbo].[ENTRADAS_MAQUINARIA_EQUIPO] (
    [ID_MAQ_EQ]             INT             IDENTITY (1, 1) NOT NULL,
    [FACTURA]               VARCHAR (50)    NULL,
    [FECHA_ENTREGA]         DATETIME        NULL,
    [FOLIO_IMPORTACION]     BIGINT          NULL,
    [ID_CUENTA_CONTABLE]    INT             NULL,
    [NO_REQ_EXTRA]          VARCHAR (250)   NULL,
    [OC]                    VARCHAR (50)    NULL,
    [PEDIMENTO]             VARCHAR (50)    NULL,
    [IMPORTE]               DECIMAL (10, 4) NULL,
    [ID_PROVEEDOR]          INT             NULL,
    [IDENTIFICACION_MAQ_EQ] VARCHAR (250)   NULL,
    CONSTRAINT [PK_ENTRADAS_MAQUINARIA_EQUIPO] PRIMARY KEY CLUSTERED ([ID_MAQ_EQ] ASC),
    CONSTRAINT [FK_ENTRADAS_MAQUINARIA_EQUIPO_CUENTAS_CONTABLES] FOREIGN KEY ([ID_CUENTA_CONTABLE]) REFERENCES [dbo].[CUENTAS_CONTABLES] ([ID_CUENTA_CONTABLE]),
    CONSTRAINT [FK_ENTRADAS_MAQUINARIA_EQUIPO_PROVEEDORES] FOREIGN KEY ([ID_PROVEEDOR]) REFERENCES [dbo].[PROVEEDORES] ([ID_PROVEEDOR])
);
